# Generated by Django 4.2.11 on 2025-01-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmStructureRegistry', '0005_auto_20250121_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'cmStructureRegistry',
                'permissions': (('basic_access', 'Can view structure registry and timers'), ('manage_structures', 'Can add structures and set fits and vulnerabilities'), ('manage_timers', 'Can add timers and set FCs'), ('delete_structure', 'Can remove structures'), ('delete_timer', 'Can delete timer')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='alliance',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='constellation',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='corporation',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='corptimer',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='corptimerview',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='solarsystem',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='structureregistry',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='structureregistryfit',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='structureregistryview',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='structuretype',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='timerstructuretype',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='timertype',
            options={'default_permissions': ()},
        ),
    ]
