# Generated by Django 4.2.11 on 2025-02-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmStructureRegistry', '0006_general_alter_alliance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timerhostility',
            options={'default_permissions': ()},
        ),
    ]
