# Generated by Django 4.2.11 on 2025-02-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmStructureRegistry', '0007_alter_timerhostility_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSystemJump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_solar_system_id', models.IntegerField()),
                ('to_solar_system_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cm_solar_system_jump',
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='solarsystemjump',
            constraint=models.UniqueConstraint(fields=('from_solar_system_id', 'to_solar_system_id'), name='cm_unique_solar_system_jump'),
        ),
    ]
