# Generated by Django 4.2.11 on 2025-03-28 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmStructureRegistry', '0012_structureregistry_pos_online'),
    ]

    operations = [
        migrations.RunSQL(
            """
                CREATE OR REPLACE
                ALGORITHM = UNDEFINED VIEW `cm_structure_registry_view` AS
                select
                    `csr`.`structure_id` AS `structure_id`,
                    `csr`.`structure_name` AS `structure_name`,
                    `csr`.`structure_type_id` AS `structure_type_id`,
                    `csr`.`solar_system_id` AS `solar_system_id`,
                    `cst`.`name` AS `structure_type`,
                    `css`.`name` AS `solar_system`,
                    `cc`.`id` AS `constellation_id`,
                    `cc`.`name` AS `constellation`,
                    `cc`.`region_id` AS `region_id`,
                    `corp`.`corporation_ticker` AS `corporation`,
                    `corp`.`corporation_id` AS `corporation_id`,
                    `ca`.`alliance_ticker` AS `alliance`,
                    `ca`.`alliance_id` AS `alliance_id`,
                    `fit`.`fit_json` AS `fit_json`,
                    `fit`.`modified_date` AS `fit_updated`,
                    `ee`.`character_name` AS `fit_updated_by`,
                    `csr`.`vulnerability_updated` AS `vulnerability_updated`,
                    `ee2`.`character_name` AS `vulnerability_updated_by`,
                    (case
                        when (`csr`.`next_vulnerability_date` < utc_timestamp()) then `csr`.`next_vulnerability`
                        else `csr`.`vulnerability`
                    end) AS `vulnerability`,
                    (case
                        when (`csr`.`next_vulnerability_date` > utc_timestamp()) then `csr`.`next_vulnerability`
                        else NULL
                    end) AS `next_vulnerability`,
                    (case
                        when (`csr`.`next_vulnerability_date` > utc_timestamp()) then `csr`.`next_vulnerability_date`
                        else NULL
                    end) AS `next_vulnerability_date`,
                    (case
                        when (`fit`.`modified_date` < `csr`.`vulnerability_updated`) then `fit`.`modified_date`
                        else `csr`.`vulnerability_updated`
                    end) AS `reviewed_date`,
                    `ee3`.`character_name` AS `reviewed_by`,
                    `tmr`.`timer_datetime` AS `timer_datetime`,
                    (case
                        when (`csr`.`removed_date` is not null) then 'REMOVED'
                        else coalesce(`tmr`.`timer_type_name`, '')
                    end) AS `timer_type`,
                    `csr`.`removed_date` AS `removed_date`,
                    `csr`.`pos_online` as `pos_online`
                from
                    ((((((((((`cm_structure_registry` `csr`
                join `cm_timer_structure_type` `cst` on
                    ((`cst`.`id` = `csr`.`structure_type_id`)))
                join `cm_solar_system` `css` on
                    ((`css`.`id` = `csr`.`solar_system_id`)))
                join `cm_constellation` `cc` on
                    ((`cc`.`id` = `css`.`constellation_id`)))
                join `eveonline_evecorporationinfo` `corp` on
                    ((`corp`.`corporation_id` = `csr`.`corporation_id`)))
                left join `eveonline_eveallianceinfo` `ca` on
                    ((`ca`.`id` = `corp`.`alliance_id`)))
                left join `cm_structure_registry_fit` `fit` on
                    ((`fit`.`structure_id` = `csr`.`structure_id`)))
                left join `eveonline_evecharacter` `ee` on
                    ((`ee`.`character_id` = `fit`.`character_id`)))
                left join `eveonline_evecharacter` `ee2` on
                    ((`ee2`.`character_id` = `csr`.`vulnerability_character_id`)))
                left join `eveonline_evecharacter` `ee3` on
                    ((`ee3`.`character_id` = `csr`.`reviewed_character_id`)))
                left join (
                    select
                        `cct`.`timer_datetime` AS `timer_datetime`,
                        `ctt`.`name` AS `timer_type_name`,
                        `cct`.`structure_id` AS `structure_id`,
                        row_number() OVER (PARTITION BY `cct`.`structure_id`
                    ORDER BY
                        `cct`.`timer_datetime` ) AS `row_num`
                    from
                        (`cm_corp_timer` `cct`
                    join `cm_timer_type` `ctt` on
                        ((`ctt`.`id` = `cct`.`timer_type_id`)))
                    where
                        (`cct`.`timer_datetime` > utc_timestamp())) `tmr` on
                    (((`tmr`.`structure_id` = `csr`.`structure_id`)
                        and (`tmr`.`row_num` = 1))));
                                            """,
            reverse_sql="DROP VIEW `cm_structure_registry_view`;"
        ),        
    ]
