# Generated by Django 4.2.11 on 2025-03-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmStructureRegistry', '0013_auto_20250328_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cm_pos_type',
                'default_permissions': (),
            },
        ),
    ]
