# Generated by Django 4.2.11 on 2025-04-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmStructureRegistry', '0014_postype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerPermissionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cm_timer_permission_type',
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can view structure registry and lowest level timers'), ('manage_structures', 'Can add structures and set fits and vulnerabilities'), ('manage_timers', 'Can add timers and set FCs'), ('delete_structure', 'Can remove structures'), ('delete_timer', 'Can delete timer'), ('skirmish_timer', 'Can view and add timers with skirmish level setting'), ('tactical_timer', 'Can view and add timers with tactical level setting')), 'verbose_name': 'cmStructureRegistry'},
        ),
    ]
