# Generated by Django 4.2.11 on 2025-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmStructureRegistry', '0015_timerpermissiontype_alter_general_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='corptimer',
            name='timer_level_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerpermissiontype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
