# Generated by Django 4.2.11 on 2025-05-04 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmStructureRegistry', '0016_corptimer_timer_level_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corptimer',
            old_name='timer_level_id',
            new_name='timer_permission_id',
        ),
    ]
