# Generated by Django 4.2.11 on 2025-05-05 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmStructureRegistry', '0017_rename_timer_level_id_corptimer_timer_permission_id'),
    ]

    operations = [
        migrations.RunSQL(
            """
                CREATE OR REPLACE
                ALGORITHM = UNDEFINED VIEW `cm_corp_timer_view` AS
                select
                    `ct`.`id` AS `id`,
                    `ct`.`system_id` AS `system_id`,
                    `ct`.`timer_type_id` AS `timer_type_id`,
                    `ct`.`timer_datetime` AS `timer_datetime`,
                    `ct`.`comment` AS `comment`,
                    `ct`.`created_by_id` AS `created_by_id`,
                    `ct`.`created_date` AS `created_date`,
                    `ct`.`hostility_type_id` AS `hostility_type_id`,
                    `ct`.`structure_type_id` AS `structure_type_id`,
                    `tst`.`name` AS `structure_type`,
                    `s`.`name` AS `solar_system`,
                    `tt`.`name` AS `timer_type_name`,
                    `ee`.`character_name` AS `created_by`,
                    `ct`.`structure_id` AS `structure_id`,
                    `ct`.`fleet_commander` AS `fleet_commander`,
                    coalesce(`csr`.`structure_name`, `ct`.`planet`) AS `structure_name`,
                    coalesce(`ct`.`timer_permission_id`, 0) as `timer_permission_id`
                from
                    (((((`cm_corp_timer` `ct`
                join `cm_solar_system` `s` on
                    ((`s`.`id` = `ct`.`system_id`)))
                join `cm_timer_type` `tt` on
                    ((`tt`.`id` = `ct`.`timer_type_id`)))
                join `eveonline_evecharacter` `ee` on
                    ((`ee`.`character_id` = `ct`.`created_by_id`)))
                left join `cm_timer_structure_type` `tst` on
                    ((`tst`.`id` = `ct`.`structure_type_id`)))
                left join `cm_structure_registry` `csr` on
                    ((`csr`.`structure_id` = `ct`.`structure_id`)));
                            """,
            reverse_sql="DROP VIEW `cm_corp_timer_view`;"
        ),
    ]