# Generated by Django 4.2.24 on 2025-10-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmStructureRegistry', '0018_auto_20250505_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='corptimer',
            name='notification_id',
            field=models.BigIntegerField(default=None),
        ),
    ]
