# Generated by Django 4.2.24 on 2025-10-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmStructureRegistry', '0019_corptimer_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corptimer',
            name='notification_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
